#!/usr/bin/env python3
"""Thin Colab-only ComfyUI adapter.

This script intentionally does not build a ComfyUI prompt graph by hand.
It accepts an adapter_request.json generated by `ltx-runner prepare-run`.
The actual ComfyUI execution implementation is completed on Colab, where
ComfyUI and its LTX custom nodes are installed.
"""

import argparse
import json
import sys
from pathlib import Path


REQUIRED_REQUEST_FIELDS = {
    "schema_version",
    "backend",
    "comfy_root",
    "job_dir",
    "workflow_path",
    "output_path",
    "required_success_files",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--request", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    request_path = Path(args.request)
    request = json.loads(request_path.read_text())
    missing = sorted(REQUIRED_REQUEST_FIELDS - set(request))
    if missing:
        print(json.dumps({"status": "error", "code": "invalid_request", "missing": missing}))
        return 2
    if request["backend"] != "comfyui_headless":
        print(json.dumps({"status": "error", "code": "unsupported_backend"}))
        return 2

    workflow_path = Path(request["workflow_path"])
    if not workflow_path.exists():
        print(json.dumps({"status": "error", "code": "missing_workflow", "path": str(workflow_path)}))
        return 2

    if args.dry_run:
        print(json.dumps({
            "status": "ok",
            "mode": "dry_run",
            "workflow_path": str(workflow_path),
            "output_path": request["output_path"],
        }))
        return 0

    print(json.dumps({
        "status": "error",
        "code": "not_implemented",
        "message": "ComfyUI execution must be enabled and tested on Colab.",
    }))
    return 8


if __name__ == "__main__":
    raise SystemExit(main())
