#!/usr/bin/env python3
import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--variant", required=True)
    parser.add_argument("--model-dir", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    model_dir = Path(args.model_dir)
    gemma = model_dir / "gemma-3-12b-it-qat-q4_0-unquantized"
    spatial = model_dir / "ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
    paths = {
        "ltx2_3_full": model_dir / "ltx-2.3-22b-dev.safetensors",
        "ltx2_3_fp8": model_dir / "ltx-2.3-22b-dev-fp8.safetensors",
        "ltx2_3_distilled_fp8": model_dir / "ltx-2.3-22b-distilled-fp8.safetensors",
        "ltx2_3_distilled": model_dir / "ltx-2.3-22b-distilled.safetensors",
    }
    enabled = args.variant
    if enabled not in paths:
        raise SystemExit(f"unsupported variant: {enabled}")

    def entry(key, display, checkpoint, supports_audio, fp8, preferred, notes):
        return f'''
[models.{key}]
display_name = "{display}"
checkpoint_path = "{checkpoint}"
config_path = ""
gemma_root = "{gemma}"
text_encoder_path = ""
vae_path = ""
spatial_upsampler_path = "{spatial}"
temporal_upsampler_path = ""
supports_audio = {str(supports_audio).lower()}
supports_t2v = true
supports_i2v = true
supports_fp8_cast = {str(fp8).lower()}
supports_fp8_scaled_mm = false
quantization = "{'fp8-cast' if fp8 else 'none'}"
preferred_profiles = {preferred}
notes = "{notes}"
'''

    registry = "# Generated by scripts/download_models_colab.sh. Re-run after changing LTX_DOWNLOAD_VARIANT.\n"
    registry += entry(
        "ltx2_3_full",
        "LTX 2.3 full",
        paths["ltx2_3_full"] if enabled == "ltx2_3_full" else "",
        True,
        False,
        '["colab_quality"]',
        "Configured only when downloaded.",
    )
    registry += entry(
        "ltx2_3_fp8",
        "LTX 2.3 FP8",
        paths["ltx2_3_fp8"] if enabled == "ltx2_3_fp8" else "",
        True,
        True,
        '["colab_balanced", "colab_quality"]',
        "Configured only when downloaded.",
    )
    registry += entry(
        "ltx2_3_distilled_fp8",
        "LTX 2.3 distilled FP8",
        paths["ltx2_3_distilled_fp8"] if enabled == "ltx2_3_distilled_fp8" else "",
        False,
        True,
        '["colab_tiny", "colab_eco", "colab_balanced"]',
        "Configured only when downloaded.",
    )
    registry += entry(
        "ltx2_3_distilled",
        "LTX 2.3 distilled",
        paths["ltx2_3_distilled"] if enabled == "ltx2_3_distilled" else "",
        False,
        False,
        '["colab_tiny", "colab_eco", "colab_balanced"]',
        "BF16 distilled variant. Use when FP8 is unavailable or not desired.",
    )
    registry += '''
[models.ltxv_13b_distilled_fp8]
display_name = "LTXV 13B distilled FP8 fallback"
checkpoint_path = ""
config_path = ""
gemma_root = ""
text_encoder_path = ""
vae_path = ""
spatial_upsampler_path = ""
temporal_upsampler_path = ""
supports_audio = false
supports_t2v = true
supports_i2v = true
supports_fp8_cast = true
supports_fp8_scaled_mm = false
quantization = "fp8-cast"
preferred_profiles = ["colab_tiny", "colab_eco"]
notes = "Optional fallback. Not downloaded by default."
'''
    Path(args.output).write_text(registry, encoding="utf-8")


if __name__ == "__main__":
    main()
