#!/usr/bin/env python3
import argparse
from pathlib import Path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--variant", required=True)
    parser.add_argument("--model-dir", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    model_dir = Path(args.model_dir)
    gemma = model_dir / "gemma-3-12b-it-qat-q4_0-unquantized"
    spatial = model_dir / "ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
    paths = {
        "ltx2_3_full": model_dir / "ltx-2.3-22b-dev.safetensors",
        "ltx2_3_fp8": model_dir / "ltx-2.3-22b-dev-fp8.safetensors",
        "ltx2_3_dev_fp8_distilled_lora": model_dir / "ltx-2.3-22b-dev-fp8.safetensors",
        "ltx2_3_distilled_fp8": model_dir / "ltx-2.3-22b-distilled-fp8.safetensors",
        "ltx2_3_distilled": model_dir / "ltx-2.3-22b-distilled.safetensors",
        "sulphur_2_dev_bf16": model_dir / "sulphur_dev_bf16.safetensors",
        "sulphur_2_dev_fp8mixed": model_dir / "sulphur_dev_fp8mixed.safetensors",
        "sulphur_2_distil_bf16": model_dir / "sulphur_distil_bf16.safetensors",
    }
    distilled_lora = model_dir / "ltx-2.3-22b-distilled-lora-384.safetensors"
    enabled = args.variant
    if enabled not in paths:
        raise SystemExit(f"unsupported variant: {enabled}")

    def entry(
        key,
        display,
        checkpoint,
        supports_audio,
        preferred,
        notes,
        spatial_path=None,
        supports_fp8_cast=False,
        supports_fp8_scaled_mm=False,
        quantization="none",
        lora_path="",
        lora_strength="0.0",
    ):
        if spatial_path is None:
            spatial_path = spatial
        return f'''
[models.{key}]
display_name = "{display}"
checkpoint_path = "{checkpoint}"
config_path = ""
gemma_root = "{gemma}"
text_encoder_path = ""
vae_path = ""
spatial_upsampler_path = "{spatial_path}"
temporal_upsampler_path = ""
lora_path = "{lora_path}"
lora_strength = {lora_strength}
supports_audio = {str(supports_audio).lower()}
supports_t2v = true
supports_i2v = true
supports_fp8_cast = {str(supports_fp8_cast).lower()}
supports_fp8_scaled_mm = {str(supports_fp8_scaled_mm).lower()}
quantization = "{quantization}"
preferred_profiles = {preferred}
notes = "{notes}"
'''

    registry = "# Generated by scripts/download_models_colab.sh. Re-run after changing LTX_DOWNLOAD_VARIANT.\n"
    registry += entry(
        "ltx2_3_full",
        "LTX 2.3 full",
        paths["ltx2_3_full"] if enabled == "ltx2_3_full" else "",
        True,
        '["colab_quality"]',
        "Configured only when downloaded.",
    )
    registry += entry(
        "ltx2_3_fp8",
        "LTX 2.3 FP8",
        paths["ltx2_3_fp8"] if enabled == "ltx2_3_fp8" else "",
        True,
        '["colab_balanced", "colab_quality"]',
        "Configured only when downloaded. FP8 dev checkpoint; load without an additional fp8-cast pass.",
    )
    registry += entry(
        "ltx2_3_dev_fp8_distilled_lora",
        "LTX 2.3 dev FP8 + distilled LoRA",
        paths["ltx2_3_dev_fp8_distilled_lora"] if enabled == "ltx2_3_dev_fp8_distilled_lora" else "",
        True,
        '["colab_tiny", "colab_eco", "colab_balanced", "colab_quality"]',
        "ComfyUI-style setup: official dev FP8 checkpoint plus distilled LoRA. Preferred Colab default; load without an additional fp8-cast pass.",
        lora_path=distilled_lora if enabled == "ltx2_3_dev_fp8_distilled_lora" else "",
        lora_strength="1.0" if enabled == "ltx2_3_dev_fp8_distilled_lora" else "0.0",
    )
    registry += entry(
        "ltx2_3_distilled_fp8",
        "LTX 2.3 distilled FP8",
        paths["ltx2_3_distilled_fp8"] if enabled == "ltx2_3_distilled_fp8" else "",
        False,
        '["colab_tiny", "colab_eco", "colab_balanced"]',
        "Configured only when downloaded. FP8 checkpoint; load without an additional fp8-cast pass.",
    )
    registry += entry(
        "ltx2_3_distilled",
        "LTX 2.3 distilled",
        paths["ltx2_3_distilled"] if enabled == "ltx2_3_distilled" else "",
        False,
        '["colab_tiny", "colab_eco", "colab_balanced"]',
        "BF16 distilled variant. Use when FP8 is unavailable or not desired.",
    )
    registry += entry(
        "sulphur_2_dev_bf16",
        "Sulphur 2 dev BF16",
        paths["sulphur_2_dev_bf16"] if enabled == "sulphur_2_dev_bf16" else "",
        True,
        '["colab_quality"]',
        "Community LTX 2.3-derived full model. Use explicitly with --model sulphur_2_dev_bf16.",
        spatial_path="",
    )
    registry += entry(
        "sulphur_2_dev_fp8mixed",
        "Sulphur 2 dev FP8 mixed",
        paths["sulphur_2_dev_fp8mixed"] if enabled == "sulphur_2_dev_fp8mixed" else "",
        True,
        '["colab_balanced", "colab_quality"]',
        "Experimental community LTX 2.3-derived FP8 mixed full model. Use explicitly with --model sulphur_2_dev_fp8mixed. Loaded without additional fp8-cast until visually validated.",
        spatial_path="",
    )
    registry += entry(
        "sulphur_2_distil_bf16",
        "Sulphur 2 distil BF16",
        paths["sulphur_2_distil_bf16"] if enabled == "sulphur_2_distil_bf16" else "",
        False,
        '["colab_tiny", "colab_eco", "colab_balanced"]',
        "Community LTX 2.3-derived distilled model. Use explicitly with --model sulphur_2_distil_bf16.",
    )
    registry += '''
[models.ltxv_13b_distilled_fp8]
display_name = "LTXV 13B distilled FP8 fallback"
checkpoint_path = ""
config_path = ""
gemma_root = ""
text_encoder_path = ""
vae_path = ""
spatial_upsampler_path = ""
temporal_upsampler_path = ""
supports_audio = false
supports_t2v = true
supports_i2v = true
supports_fp8_cast = false
supports_fp8_scaled_mm = false
quantization = "none"
preferred_profiles = ["colab_tiny", "colab_eco"]
notes = "Optional FP8 fallback. Not downloaded by default; load without an additional fp8-cast pass."
'''
    Path(args.output).write_text(registry, encoding="utf-8")


if __name__ == "__main__":
    main()
